# Generated by Django 5.2.1 on 2025-06-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('purpose', models.TextField(verbose_name='الغرض')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('start_time', models.TimeField(verbose_name='الوقت البدء')),
                ('end_time', models.TimeField(verbose_name='الوقت الانتهاء')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='الملاحظات')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
        ),
    ]
