# Generated by Django 5.2.1 on 2025-06-01 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الشركة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'شركة',
                'verbose_name_plural': 'الشركات',
            },
        ),
        migrations.AlterModelOptions(
            name='bookingrequest',
            options={'verbose_name': 'طلب حجز', 'verbose_name_plural': 'طلبات الحجز'},
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='room',
            field=models.CharField(blank=True, choices=[('room1', 'قاعة الاجتماعات الرئيسية'), ('room2', 'قاعة  تدريب مجموعة مارينا')], max_length=10, null=True, verbose_name='القاعة'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='end_time',
            field=models.TimeField(verbose_name='وقت الانتهاء'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='start_time',
            field=models.TimeField(verbose_name='وقت البدء'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.company', verbose_name='الشركة'),
        ),
    ]
