# Generated by Django 5.2.1 on 2026-01-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_company_alter_bookingrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='door_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رمز الباب'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='room',
            field=models.CharField(blank=True, choices=[('room1', 'قاعة الاجتماعات الرئيسية/13 شخص'), ('room2', 'قاعة  تدريب مجموعة مارينا/20 شخص')], max_length=10, null=True, verbose_name='القاعة'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=10, verbose_name='الحالة'),
        ),
    ]
